config/routes.rb
Rails.application.routes.draw do
  resources :image_files

  root 'image_files#new'

end

app/models/image_file.rb
class ImageFile < ActiveRecord::Base
	attr_accessor :png_file, :width_offset, :height_offset

	validates :name, presence: true
	validates :name, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/image_files_controller.rb
class ImageFilesController < ApplicationController
  before_action :set_image_file, only: [:show, :edit, :update, :destroy]

  # GET /image_files
  # GET /image_files.json
  def index
    @image_files = ImageFile.all
  end

  # GET /image_files/1
  # GET /image_files/1.json
  def show
  end

  # GET /image_files/new
  def new
    @image_file = ImageFile.new
  end

  # GET /image_files/1/edit
  def edit

  end

  # POST /image_files
  # POST /image_files.json
  def create
    @image_file = ImageFile.new(image_file_params)

    image = MiniMagick::Image.open(image_file_params[:png_file].tempfile.path)  

    @image_file.height = image["height"]
    @image_file.width = image["width"]
    @image_file.name = @image_file.name+'.png'
    image.write "public/images/#{@image_file.name}"

    respond_to do |format|
      if @image_file.save
        format.html { redirect_to @image_file, notice: 'Image file was successfully created.' }
        format.json { render :show, status: :created, location: @image_file }
      else
        format.html { render :new }
        format.json { render json: @image_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /image_files/1
  # PATCH/PUT /image_files/1.json
  def update

    respond_to do |format|
      if @image_file.update(image_file_params)
        image = MiniMagick::Image.open('public/images/'+@image_file.name) 
        image.crop "#{@image_file.width}x#{@image_file.height}+#{@image_file.width_offset}+#{@image_file.height_offset}!"
        image.write "public/images/#{@image_file.name}"
        format.html { redirect_to @image_file, notice: 'Image file was successfully updated.' }
        format.json { render :show, status: :ok, location: @image_file }
      else
        format.html { render :edit }
        format.json { render json: @image_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /image_files/1
  # DELETE /image_files/1.json
  def destroy
    File.unlink('public/images/'+@image_file.name)
    @image_file.destroy
    respond_to do |format|
      format.html { redirect_to image_files_url, notice: 'Image file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image_file
      @image_file = ImageFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_file_params
      params.require(:image_file).permit(:name, :height, :width, :png_file, :height_offset, :width_offset)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_files_helper.rb
module ImageFilesHelper
end

app/views/image_files/_form.html.erb
<%= form_for(@image_file) do |f| %>
  <% if @image_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image_file.errors.count, "error") %> prohibited this image_file from being saved:</h2>

      <ul>
      <% @image_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @image_file.id.present? %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <br>

    <div class="field">
      <%= f.label :png_file %>
      <%= f.file_field :png_file %>
    </div>
    <br>
  <% end %>

  <% if @image_file.id.present? %>
    <div class="field">
      <%= f.label :height %><br>
      <%= f.text_field :height %>
    </div>
    <div class="field">
      <%= f.label :width %><br>
      <%= f.text_field :width %>
    </div>
    <div class="field">
      <%= f.label :width_offset %><br>
      <%= f.text_field :width_offset %>
    </div>
    <div class="field">
      <%= f.label :height_offset %><br>
      <%= f.text_field :height_offset %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/image_files/edit.html.erb
<h1>Editing image_file</h1>

<%= image_tag @image_file.name %>

<%= render 'form' %>

<%= link_to 'Show', @image_file %> |
<%= link_to 'Back', image_files_path %>

<script>

$(document).ready(function(){

	var left, right, top, bottom;
	var $img = $('img');

	// Offset
	var offset = $img.offset();

	$img.on('mousedown', function(event){

		event.preventDefault();

		left = event.pageX;
		top = event.pageY;
		
		$(this).on('mouseup', function(event){
			right = event.pageX;
			bottom = event.pageY;
		
			// Set end result
			var newTop = Math.ceil(top - offset.top);
			var newLeft = Math.ceil(left - offset.left);
			var width = Math.ceil(right - left);
			var height = Math.ceil(bottom - top);


			$('#image_file_width_offset').val(newLeft);
			$('#image_file_height_offset').val(newTop);
			$('#image_file_width').val(width);
			$('#image_file_height').val(height);
		});
	});


});

</script>

app/views/image_files/index.html.erb
<h1>Listing image_files</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Width</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @image_files.each do |image_file| %>
      <tr>
        <td><%= image_file.name %></td>
        <td><%= image_file.height %></td>
        <td><%= image_file.width %></td>
        <td><%= link_to 'Show', image_file %></td>
        <td><%= link_to 'Edit', edit_image_file_path(image_file) %></td>
        <td><%= link_to 'Destroy', image_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image file', new_image_file_path %>

app/views/image_files/new.html.erb
<h1>New image_file</h1>

<%= render 'form' %>

<%= link_to 'Back', image_files_path %>

app/views/image_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= image_tag @image_file.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @image_file.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @image_file.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @image_file.width %>
</p>

<%= link_to 'Edit', edit_image_file_path(@image_file) %> |
<%= link_to 'Back', image_files_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>